# DS 3000/CS 3200 Lab 1

Due: Tuesday May 13 in-class

### Submission Instructions
Upload this `ipynb` file to GitHub, and then to Gradescope.  To ensure that your submitted `ipynb` file represents your latest code, make sure to give a fresh `Kernel > Restart & Run All` just before uploading the `ipynb` file to GitHub and verify that the correct version is represented on Gradescope.

### Tips for success
- Collaborate: bounce ideas off of each other, if you are having trouble you can ask your classmates or Dr. Gerber for help with specific issues, however...
- [(See)](http://www.northeastern.edu/osccr/academic-integrity), i.e. you are welcome to **talk about/discuss** (*not* show or allow each other to copy your answers to) the problems.

# Part 1 (40 points): Intro to Markdown

Use the markdown language below to create your own brief wikipedia-esque description of a topic related to International Government and Politics. 

Your mini-wiki page must include:
- three headers: a title, subtitle and subsubtitle (the #, ##, ### syntax)
- an embedded image from a web address (use an [image hosting site](https://makeawebsitehub.com/free-photo-hosting/) if you'd like to upload your own)
- a **markdown** table of size at least 9 cells (i.e. 3 by 3, or 5 by 2)
- a list in **markdown**
- a link to another website

To practice typing in math mode, also include a LaTeX formula describing how your final grade is going to be calculated based on the syllabus, something like:

$$updatedgradeindatabasescourse = 0.60*homeworksandlabs + 0.40*inclassactivities$$

Please be **brief** in your text.  Aim for roughly 3 sentences total of text.

------

# Political Polarization

*The heightening of tensions and hatred between political parties.*

![Extremism Graph](https://www.facinghistory.org/sites/default/files/styles/scale_480/public/2024-08/Pew_research_graphs.jpg?itok=hbIG7Pcl)

## History
### Social Media
It started with social media.
### Donald Trump Era
As media companies seek profit, they release big headlines about the rather large personality in office.

| Irrelevant | Markdown | Table |
|----------|----------|----------|
| Joseph   | R.       | Biden   |
|    test  | Donald   | J. Trump   |

Polarization is increased by:
- Social Media
- Global Events
- Politicians
- Political Strategy
- Lack of Human Dignity

Learn more about this concept at [the actual Wikipedia page](https://en.wikipedia.org/wiki/Political_polarization).

My Grade for CS3200:
$$grade = 0.60*homeworksandlabs + 0.40*inclassactivities$$



------

# Part 2: Numpy
## Part 2.1: Creating Arrays (10 points)

Create the following two arrays using the NumPy library and then print them out. Call the first array `array_a` and the second array `array_b` (make sure you keep the `import` statement below):

$$\mathbf{array_a} = \begin{bmatrix}3 & 8 & -2 & 3\\
.5 & -1 & 6 & 4\\
-5 & 7 & -42 & 2
\end{bmatrix}$$

$$\mathbf{array_b} = \begin{bmatrix}42 & 38 & 34\\
30 & 26 & 22\\
18 & 14 & 10\\
6 & 2 & -2\\
-6 & -10 & -14
\end{bmatrix}$$

In [1]:
# make sure to import numpy library
import numpy as np

In [2]:
array_a = np.array([[3,8,-2,3],
                    [.5,-1,6,4],
                    [-5,7,-42,2]])

array_b = np.array([[42,38,34],
                   [30,26,22],
                   [18,14,10],
                   [6,2,-2],
                   [-6,-10,-14]])


In [3]:
# uncomment below to print array_a
array_a

array([[  3. ,   8. ,  -2. ,   3. ],
       [  0.5,  -1. ,   6. ,   4. ],
       [ -5. ,   7. , -42. ,   2. ]])

In [4]:
# uncomment below to print array_b
array_b

array([[ 42,  38,  34],
       [ 30,  26,  22],
       [ 18,  14,  10],
       [  6,   2,  -2],
       [ -6, -10, -14]])

## Part 2.2: Exploring Arrays (15 points)

1. Give the shape, size, ndim, and nbytes for each of the two arrays.
1. Take the transpose of both arrays. Call these `t_array_a` and `t_array_b`.
1. Try to add `array_a` and `t_array_b` (*prove* and *show* you did this with commented out code), then remove the last column of `t_array_b` and try to add them again. In a markdown cell, explain what happened.

In [5]:
array_a.shape

(3, 4)

In [6]:
array_b.shape

(5, 3)

In [7]:
array_a.size

12

In [8]:
array_b.size

15

In [9]:
array_a.ndim

2

In [10]:
array_b.ndim

2

In [11]:
array_a.nbytes

96

In [12]:
array_b.nbytes

120

In [13]:
t_array_a = np.transpose(array_a)
t_array_b = np.transpose(array_b)

# Other kids are doing array_a.T as well, which is cleaner I suppose...

In [14]:
t_array_a

array([[  3. ,   0.5,  -5. ],
       [  8. ,  -1. ,   7. ],
       [ -2. ,   6. , -42. ],
       [  3. ,   4. ,   2. ]])

In [15]:
t_array_b

array([[ 42,  30,  18,   6,  -6],
       [ 38,  26,  14,   2, -10],
       [ 34,  22,  10,  -2, -14]])

In [16]:
# array_a + t_array_b
# ValueError: operands could not be broadcast together with shapes (3,4) (3,5)

t_array_b_trimmed = t_array_b[:,:-1]
t_array_b_trimmed

array([[42, 30, 18,  6],
       [38, 26, 14,  2],
       [34, 22, 10, -2]])

In [17]:
added = array_a + t_array_b_trimmed
added

array([[ 45. ,  38. ,  16. ,   9. ],
       [ 38.5,  25. ,  20. ,   6. ],
       [ 29. ,  29. , -32. ,   0. ]])

### Explanation
The shapes did not align before, so we had to remove a column to make it work.

# Part 3: Pandas
## Part 3.1: Reading in Data (5 points)

On Canvas is the `train_stations_europe.csv` file. It was adapted from [this Kaggle data set](https://www.kaggle.com/datasets/headsortails/train-stations-in-europe). Read this data set in, using the `id` as the index column, and print the first few rows of the data. Make sure you keep the `import` statement below!

In [18]:
# make sure to import pandas library
import pandas as pd

df = pd.read_csv("train_stations_europe.csv", index_col="id")
df.head()

name   latitude  longitude  parent_station_id country  \
id                                                                             
1   Chateau-Arnoux-St-Auban  44.081790   6.001625                NaN      FR   
2   Chateau-Arnoux-St-Auban  44.061565   5.997373                1.0      FR   
3     Chateau-Arnoux Mairie  44.063863   6.011248                1.0      FR   
4           Digne-les-Bains  44.350000   6.350000                NaN      FR   
6           Digne-les-Bains  44.088710   6.222982                4.0      FR   

       time_zone  is_city  is_main_station  is_airport  
id                                                      
1   Europe/Paris     True            False       False  
2   Europe/Paris    False             True       False  
3   Europe/Paris    False            False       False  
4   Europe/Paris     True            False       False  
6   Europe/Paris    False             True       False

## Part 3.2: Manipulating Data (20 points)

1. Create a subset of the data set which (a) **includes** only train stations in Belgium and (b) **excludes** all train stations which are **not** in a city. Make sure to save this subset as a new data frame and print the first few rows of the data.
1. Use the `.describe()` function to produce summary statistics for the subset from the previous part. Create a markdown cell and explain:
    - What Series did the `.describe()` function run on? What Series did it not run on? What is the difference, and what does this mean the `.describe()` function is used for?

In [19]:
belgium_cities = df[(df["country"] == "BE") & (df["name"].notna())]
belgium_cities.head()

name   latitude  longitude  parent_station_id country  \
id                                                                         
1121  Tournai Frontiere        NaN        NaN                NaN      BE   
1122          Froyennes        NaN        NaN                NaN      BE   
1313           Mouscron        NaN        NaN                NaN      BE   
1354    Quevy Frontiere        NaN        NaN             6003.0      BE   
5893     Bruxelles-Midi  50.835374   4.335695             5974.0      BE   

            time_zone  is_city  is_main_station  is_airport  
id                                                           
1121  Europe/Brussels    False            False       False  
1122  Europe/Brussels    False            False       False  
1313  Europe/Brussels    False            False       False  
1354  Europe/Brussels    False            False       False  
5893  Europe/Brussels    False             True       False

In [20]:
belgium_cities.describe()


latitude   longitude  parent_station_id
count  573.000000  573.000000          26.000000
mean    50.726684    4.484243       13945.846154
std      0.344564    0.709282       10417.120726
min     49.555984    2.601729        5964.000000
25%     50.497416    4.023832        5964.000000
50%     50.766157    4.411501        5974.000000
75%     50.979756    4.949406       25908.250000
max     51.462641    6.120155       29332.000000

The describe() function ran on the numeric Series in the DataFrame, such as latitude and longitude; It did not run on non-numeric Series like name, city, or country.

This is because describe() just does statistics like mean, standard deviation, min, max, and quartiles—statistics that are only meaningful for numerical data. For categorical or text data, you would need to pass include='all' or use different methods like .value_counts() to summarize those columns.

# Part 4: GitHub (10 points)

When you finish the first three parts, give one last restart and run all to this file. Then, go to the [DS 3000 GitHub](https://github.com/eaegerber/ds3000_summer25), fork it and then clone it to your local machine. Then:

- In the forked and cloned ds3000_summer25 repo, make a new branch (`git checkout -b lab-upload`)
- Create a folder with your name (as Dr. Gerber did)
- Navigate to that folder and place this jupyter notebook inside
- Add the file as the change to be committed (`git add .\Lab1_MyName.ipynb`)
- Check `git status`, your changes should be staged
- Commit the changes with a short message (`git commit -m "My message"`)
- Push the repository to GitHub (`git push origin lab-upload`)
- Navigate the the GitHub in the browser and create a pull request
- Once the pull request is merged, you can delete your branch in the "Pull Requests" tab in the browser
- Finally, upload the Lab to Gradescope. When you do so, it will give you the option to do it via GitHub; do that.