#### DS 3000/CS 3200 Lab 1

Due: Tuesday May 13 in-class

### Submission Instructions
Upload this `ipynb` file to GitHub, and then to Gradescope.  To ensure that your submitted `ipynb` file represents your latest code, make sure to give a fresh `Kernel > Restart & Run All` just before uploading the `ipynb` file to GitHub and verify that the correct version is represented on Gradescope.

### Tips for success
- Collaborate: bounce ideas off of each other, if you are having trouble you can ask your classmates or Dr. Gerber for help with specific issues, however...
- [(See)](http://www.northeastern.edu/osccr/academic-integrity), i.e. you are welcome to **talk about/discuss** (*not* show or allow each other to copy your answers to) the problems.

# Part 1 (40 points): Intro to Markdown

Use the markdown language below to create your own brief wikipedia-esque description of a topic related to International Government and Politics. 

Your mini-wiki page must include:
- three headers: a title, subtitle and subsubtitle (the #, ##, ### syntax)
- an embedded image from a web address (use an [image hosting site](https://makeawebsitehub.com/free-photo-hosting/) if you'd like to upload your own)
- a **markdown** table of size at least 9 cells (i.e. 3 by 3, or 5 by 2)
- a list in **markdown**
- a link to another website

To practice typing in math mode, also include a LaTeX formula describing how your final grade is going to be calculated based on the syllabus, something like:

$$grade = weight_1*score_1 + weight_2*score_2$$

Please be **brief** in your text.  Aim for roughly 3 sentences total of text.

# Transportation Systems In Belgium
![Train](https://admin.expatica.com/be/wp-content/uploads/sites/4/2023/11/belgium-public-transport-6.jpg)

<p>Although a smaller country in comparison to the greater EU, there are a various ways to get around! Feeling active? Bike around through pedestrian and biker friendly streets? Don't feel like driving? Take the local train or bus systems near your area.</p>

## Number of users of Each Transportation by Year
|      | Buses  | Cars   | Bikes | Trains  |
|------|--------|--------|-------|---------|
| 2000 | 100000 | 30000  | 40000 | 5000000 |
| 2010 | 90000  | 70000  | 60000 | 6000000 |
| 2020 | 40000  | 100000 | 50000 | 4000000 |

## Ranked convenience of each transportation
<ol>
  <li>Train</li>
  <li>Car</li>
  <li>Bike</li>
  <li>Bus</li>
</ol>

### Its all opinion based
<p> No matter which way you decide to get around, as long as it works for you, then your all set! If you would like to learn more please go to this link  </p> 

[Link](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.belgium.be/en/mobility/public_transport&ved=2ahUKEwj73OTe06CNAxVXSKQEHXNhAVEQFnoECBgQAQ&usg=AOvVaw1cbasGjmW2klALtaIjxG5T)


# Part 2: Numpy
## Part 2.1: Creating Arrays (10 points)

Create the following two arrays using the NumPy library and then print them out. Call the first array `array_a` and the second array `array_b` (make sure you keep the `import` statement below):

$$\mathbf{array_a} = \begin{bmatrix}3 & 8 & -2 & 3\\
.5 & -1 & 6 & 4\\
-5 & 7 & -42 & 2
\end{bmatrix}$$

$$\mathbf{array_b} = \begin{bmatrix}42 & 38 & 34\\
30 & 26 & 22\\
18 & 14 & 10\\
6 & 2 & -2\\
-6 & -10 & -14
\end{bmatrix}$$

In [1]:
# make sure to import numpy library
import numpy as np

In [2]:
array_a = np.array([[3,8,-2,3], [.5, -1,6,4], [-5, 7, -42, 2]])
array_a

array_b = np.array([[48, 38, 34], [30, 26, 22], [18,14,10], [6,2,-2], [-6,-10,-14]])
array_b

array([[ 48,  38,  34],
       [ 30,  26,  22],
       [ 18,  14,  10],
       [  6,   2,  -2],
       [ -6, -10, -14]])

In [3]:
# uncomment below to print array_a
array_a

array([[  3. ,   8. ,  -2. ,   3. ],
       [  0.5,  -1. ,   6. ,   4. ],
       [ -5. ,   7. , -42. ,   2. ]])

In [4]:
# uncomment below to print array_b
array_b

array([[ 48,  38,  34],
       [ 30,  26,  22],
       [ 18,  14,  10],
       [  6,   2,  -2],
       [ -6, -10, -14]])

## Part 2.2: Exploring Arrays (15 points)

1. Give the shape, size, ndim, and nbytes for each of the two arrays.
1. Take the transpose of both arrays. Call these `t_array_a` and `t_array_b`.
1. Try to add `array_a` and `t_array_b` (*prove* and *show* you did this with commented out code), then remove the last column of `t_array_b` and try to add them again. In a markdown cell, explain what happened.

In [5]:
def exploring_arrays(array): 
    print(array.shape)
    print(array.size)
    print(array.ndim)
    print(array.nbytes)

exploring_arrays(array_a)
exploring_arrays(array_b)

t_array_a = array_a.T
t_array_b = array_b.T

array_a
array_b
##added_array =array_a + t_array_b
##this fails

removed = t_array_b[:, :-1]
added_array =array_a + removed
added_array



(3, 4)
12
2
96
(5, 3)
15
2
120


array([[ 51. ,  38. ,  16. ,   9. ],
       [ 38.5,  25. ,  20. ,   6. ],
       [ 29. ,  29. , -32. ,   0. ]])

<p>With this added_array =array_a + t_array_b we get an error since the sizes of the arrays are not the same (3,4) vs (3, 5). In order to merge the two, we need to make the arrays the same size so we have to remove one of the columns from t_array_b. Once we call  t_array_b[:, :-1] then both arrays are the same size and can be merged now. </p>

# Part 3: Pandas
## Part 3.1: Reading in Data (5 points)

On Canvas is the `train_stations_europe.csv` file. It was adapted from [this Kaggle data set](https://www.kaggle.com/datasets/headsortails/train-stations-in-europe). Read this data set in, using the `id` as the index column, and print the first few rows of the data. Make sure you keep the `import` statement below!

In [6]:
# make sure to import pandas library
import pandas as pd

In [7]:

train_S = pd.read_csv("train_stations_europe.csv", index_col = "id")
train_S.head()

name   latitude  longitude  parent_station_id country  \
id                                                                             
1   Chateau-Arnoux-St-Auban  44.081790   6.001625                NaN      FR   
2   Chateau-Arnoux-St-Auban  44.061565   5.997373                1.0      FR   
3     Chateau-Arnoux Mairie  44.063863   6.011248                1.0      FR   
4           Digne-les-Bains  44.350000   6.350000                NaN      FR   
6           Digne-les-Bains  44.088710   6.222982                4.0      FR   

       time_zone  is_city  is_main_station  is_airport  
id                                                      
1   Europe/Paris     True            False       False  
2   Europe/Paris    False             True       False  
3   Europe/Paris    False            False       False  
4   Europe/Paris     True            False       False  
6   Europe/Paris    False             True       False

## Part 3.2: Manipulating Data (20 points)

1. Create a subset of the data set which (a) **includes** only train stations in Belgium and (b) **excludes** all train stations which are **not** in a city. Make sure to save this subset as a new data frame and print the first few rows of the data.
1. Use the `.describe()` function to produce summary statistics for the subset from the previous part. Create a markdown cell and explain:
    - What Series did the `.describe()` function run on? What Series did it not run on? What is the difference, and what does this mean the `.describe()` function is used for?

In [8]:
belgium_data = train_S.loc[(train_S['country'] == "BE") & (train_S.is_city), :]
belgium_data.head()

belgium_data['latitude'].describe()
belgium_data['parent_station_id'].describe()




count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: parent_station_id, dtype: float64

<p>The .describe() function will run on data types like booleans, ints, characters and strings but will not run on data that has NaN since there is not data to run stats on. When you use .describe() on a Series that has NaN, then you will get empty stat data in comparison to a data type that will work like ints. Describe is used to get mean, standard deviation, etc.</p> 

# Part 4: GitHub (10 points)

When you finish the first three parts, give one last restart and run all to this file. Then, go to the [DS 3000 GitHub](https://github.com/eaegerber/ds3000_summer25), fork it and then clone it to your local machine. Then:

- In the forked and cloned ds3000_summer25 repo, make a new branch (`git checkout -b lab-upload`)
- Create a folder with your name (as Dr. Gerber did)
- Navigate to that folder and place this jupyter notebook inside
- Add the file as the change to be committed (`git add .\Lab1_MyName.ipynb`)
- Check `git status`, your changes should be staged
- Commit the changes with a short message (`git commit -m "My message"`)
- Push the repository to GitHub (`git push origin lab-upload`)
- Navigate the the GitHub in the browser and create a pull request
- Once the pull request is merged, you can delete your branch in the "Pull Requests" tab in the browser
- Finally, upload the Lab to Gradescope. When you do so, it will give you the option to do it via GitHub; do that.